image: openjdk:17-alpine


# default:
#   tags:
#     - comsc-ci
#     #- general-docker


stages:
  - build
  - publish

before_script:
  - echo $GRADLE_HOME
  - echo `pwd`
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - rm -f  .gradle/caches/modules-2/modules-2.lock
  - rm -fr .gradle/caches/*/plugin-resolution/
  - chmod +x gradlew
cache:
  key: gradle-cache-key
  paths:
    - .gradle/wrapper
    - .gradle/caches
  policy: pull

build:gradle:
  stage: build
  # only:
  #   - tags
  script:

    - ./gradlew --continue buildAndReport
  cache:
    key: gradle-cache-key
    paths:
      - .gradle/wrapper
      - .gradle/caches
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - ./build/classes/java/main
      - ./build/reports/checkstyle/
      - ./build/jacocoHtml/
      - ./build/reports/tests/
      - ./build/libs/*.jar
      - ./build/jacoco/test.exec

    expire_in: 4 week

pages:

  stage: publish
  # only:
  #   - tags

  script:
    - pwd
    - mkdir --parents public/build/libs
    - mv ./build/reports/tests/ public
    - mv ./build/reports/checkstyle/ public
    - mv ./build/jacocoHtml/ public
    - mv ./build/libs/*.jar public/build/libs
    - pwd
    - ls -lR public

  cache:
    key: gradle-cache-key
    paths:
      - .gradle/wrapper
      - .gradle/caches

  artifacts:
    paths:
      - public

